config/routes.rb
Rails.application.routes.draw do

  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
  end
  devise_for :admins
  devise_for :users
  
  # get 'inicio', to: 'site/welcome#index'
  
  resources :sales
  resources :products
  resources :clients
  
  #root to: "site/welcome#index"
  root to: "users_backoffice/welcome#index"
  #root to: "users/users#sing_in"
   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
  # default_scope { where(deleted_at: nil) }
  scope :active, -> { where(deleted_at: nil) }
  scope :inactive, -> { where('deleted_at IS NOT NULL') }
  
  validates :name, presence: { message: "é obrigatório!"}
  validates :email, presence: { message: "é obrigatório!"}
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: %i[ show edit update destroy ]
  
  
  # GET /clients or /clients.json
  def index
    @clients = Client.active
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to clients_url, notice: "Cliente foi criado com sucesso." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to clients_url, notice: "Cliente foi editado com sucesso." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.deleted_at = DateTime.now
    respond_to do |format|
      if @client.save 
        format.html { redirect_to clients_url, notice: "Cliente foi excluído com sucesso." }
        format.json { head :no_content }
      else 
        format.html { render :index, notice: "Não foi possível excluir o Cliente." }
        format.json { render json: @client.errors }
      end    
    end
  end



  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :email, :birth_date)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%=t("messages.alert") %></h2>
      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control w-50", placeholder:"Nome"%>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control w-50", placeholder:"Email" %>
  </div>
  
  </p>
  
  <div class="form-group">
    <%= form.label :birth_date%>
    <div>
      <%= form.date_select :birth_date, {}, class: 'form-control d-inline w-auto' %>
    </div>
   
  </div>

</p>

  <div class="actions">
    <%= form.submit nil, class: "btn btn-primary"%>
    <%= link_to t('links.show'), clients_path, class: "btn btn-primary"%>
  </div>
<% end %>

</p>

app/views/clients/edit.html.erb
<h1>Editar Cliente</h1>

<%= render 'form', client: @client %>

app/views/clients/index.html.erb
<div class=" d-flex">

  <div class="col-10">
    <h1><%= Client.model_name.human(count: @clients.count)%></h1>
  </div>
  
  <div class="col-0">
    <%= link_to t('links.new_client'), new_client_path, class:"btn btn-primary float-rigth" %>
  </div>
</div>

</br>

<table class="table table-hover">
  <thead class="table-dark">
    <tr>
      <th><%= @clients.human_attribute_name(:name) %></th>
      <th><%= @clients.human_attribute_name(:email) %></th>
      <th><%= @clients.human_attribute_name(:birth_date) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.email %></td>
        <td><%= client.birth_date %></td>
        <td><%= link_to t('links.edit'), edit_client_path(client), class: "btn btn-primary" %></td>
        <td><%= link_to t('links.delete'), client, method: :delete, data: { confirm: t('messages.confirm')}, class: "btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/clients/new.html.erb
<h1>Novo Cliente</h1>

<%= render 'form', client: @client %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Data de Nascimento:</strong>
  <%= @client.birth_date %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>