config/routes.rb
Rails.application.routes.draw do

  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
  end
  devise_for :admins
  devise_for :users
  
  # get 'inicio', to: 'site/welcome#index'
  
  resources :sales
  resources :products
  resources :clients
  
  #root to: "site/welcome#index"
  root to: "users_backoffice/welcome#index"
  #root to: "users/users#sing_in"
   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :sales
  
  scope :active, -> { where(deleted_at: nil) }
  scope :inactive, -> { where('deleted_at IS NOT NULL') }
  
  has_attached_file :upload, :styles => { :medium => "300x300>", :thumb => "200x200>" } 
  validates_attachment_content_type :upload, :content_type => /\Aimage\/.*\Z/
  
  validates :name, :presence => { :message => "é obrigatório!"}
  validates :price, :presence => {:message => "é obrigatório!"}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: %i[ show edit update destroy ]
  
  
  # GET /products or /products.json
  def index
    @products = Product.active
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Produto foi criado com sucesso." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Produto foi editado com sucesso." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.deleted_at = DateTime.now
    respond_to do |format|
      if @product.save  
        format.html { redirect_to products_url, notice: "Produto foi excluido com sucesso." }
        format.json { head :no_content }
      else
        format.html { render :index, notice: "Não foi possível excluir o Produto."}
        format.json { render json: @product.errors }
      end
    end
  end

  private
    
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :upload_id, :_destroy)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, :html => {:multipart => true} do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%="Preencha os campos corretamente"%></h2>
      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control w-50", placeholder:"Nome"%>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class:"form-control w-50", placeholder:"Descrição" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class:"form-control w-50", placeholder:"Preço" %>
  </div>

  <div class="field">
    <%= form.label :upload %>
    <%= form.file_field :upload, class:"form-control w-50" %>
  </div>

</p>

  <div class="actions">
    <%= form.submit nil, class: "btn btn-primary" %>
    <%= link_to t('links.back'), products_path, { style:"float:up",  class: "btn btn-primary" } %>
  </div>
<% end %>
 
</p>

app/views/products/edit.html.erb
<h1>Editar Produto</h1>

<%= render 'form', product: @product %>

app/views/products/index.html.erb
<div class="d-flex"> 

  <div class="col-10">
    <h1><%= Product.model_name.human(count: @products.count) %></h1>
  </div>
  
  <div class="col-2">
    <%= link_to t('links.new_product'), new_product_path, class:"btn btn-primary float-right" %>
  </div>
  
</div>

</br>

<table class="table table-hover">
  <thead class="table-dark">
    <tr>
      <th><%= @products.human_attribute_name(:name) %></th>
      <th><%= @products.human_attribute_name(:description) %></th>
      <th><%= @products.human_attribute_name(:price) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= link_to t('links.edit'), edit_product_path(product), class: "btn btn-primary" %></td>
        <td><%= link_to t('links.delete'), product, method: :delete, data: { confirm: t('messages.confirm')}, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>Novo Produto</h1>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<form>

  <div class="form-group">
    <%= label_tag nil, @product.class.human_attribute_name(:name) %>
    <%= text_field_tag nil, @product.name, class:"form-control", disabled: true %>
  </div>
  

  <div class="form-group">
    <%= label_tag nil, @product.class.human_attribute_name(:description) %>
    <%= text_field_tag nil, @product.description, class:"form-control", disabled: true %>
  </div>

  <div class="form-group">
    <%= label_tag nil, @product.class.human_attribute_name(:price) %>
    <%= text_field_tag nil, @product.price, class:"form-control", disabled: true %> 
  </div>
  
  <p>
    <%= "Upload" %>
  </p>

  <p>
    <%= image_tag @product.upload.url %>
  <p>

</form>

</p>

<%= link_to t('links.edit'), edit_product_path(@product), class:"btn btn-primary" %> |
<%= link_to t('links.back'), products_path, class:"btn btn-primary" %>