config/routes.rb
Rails.application.routes.draw do

  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
  end
  devise_for :admins
  devise_for :users
  
  # get 'inicio', to: 'site/welcome#index'
  
  resources :sales
  resources :products
  resources :clients
  
  #root to: "site/welcome#index"
  root to: "users_backoffice/welcome#index"
  #root to: "users/users#sing_in"
   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :client
  has_many :sale_items
  has_many :products, through: :sale_items
  
  accepts_nested_attributes_for :sale_items, allow_destroy: true, reject_if: :all_blank

  validates :client, :presence => { :message => " é obrigatório !"}
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_sale, only: %i[ show edit update destroy ]
  before_action :set_client_options, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_product_options, only: [:new, :create, :edit, :update, :destroy]
  
  
  # GET /sales or /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1 or /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    @sale.sale_items.build
    
    set_client_options
    set_product_options
  end

  # GET /sales/1/edit
  def edit
    @sale = Sale.find params[:id]
    set_client_options
    set_product_options
  end

  # POST /sales or /sales.json
  def create
   
    @sale = Sale.new(sale_params)
    
    set_client_options
    set_product_options

    respond_to do |format|
      if @sale.save
        format.html { redirect_to sales_url, notice: "Venda foi criado com sucesso." }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to sales_url, notice: "Venda foi editada com sucesso." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: "Venda foi excluida com sucesso." }
      format.json { head :no_content }
    end
  end

  private
  
    def set_product_options
      @product_option = Product.all.pluck(:name, :id)
    end
    
    
    def set_client_options
      @client_option = Client.all.pluck(:name, :id)
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:client_id, sale_items_attributes: [:id, :product_id, :_destroy])
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for @sale do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= t("messages.alert")%></h2>
      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :client_id %>
    <%= form.select("client_id", @client_option, { include_blank: "Selecione..." }, class:"form-control w-50") %>
  </div>
  
  <div class="field">
    <%= form.fields_for :sale_items do |f| %>
      <%= render 'sale_item_fields', f: f %>
    <% end %>
  </div>
    <%= link_to_add_fields t("links.add_a_product"),form, :sale_items%>
</p>

  <div class="actions">
    <%= form.submit nil, class: "btn btn-primary"%>
    <%= link_to t('links.show'), sales_path, class: "btn btn-primary"%>
  </div>
<% end %>

</p>

<script>

$('form').on('click', '.remove-fields', function(event) {
  console.log('clicked')
    $(this).prev('input[type=hidden]').val('1');
    $(this).closest('fieldset').hide();
    return event.preventDefault();
  });
  
$('form').on('click', '.add_fields', function(event) {
    console.log('clicked!')
     var regexp, time;
     time = new Date().getTime();
     regexp = new RegExp($(this).data('id'), 'g');
     $(this).before($(this).data('fields').replace(regexp, time));
     return event.preventDefault();
    });
</script>

app/views/sales/_sale_item_fields.html.erb
<div class="form-group nested-fields">
  <fieldset style="display:flex; align-items: flex-end; gap: 12px">
    <div class="w-50">
      <%= f.label :product_id %>
      <%= f.hidden_field :_destroy %>
      <%= f.select(:product_id, Product.all.collect {|u| [u.name, u.id]}, { prompt: 'Selecione' }, { class: "form-control" } ) %>
    </div>
    
    <div>
      <%= link_to t("links.delete"), "#", { style: "float:right", class: 'remove-fields btn btn-danger' } %>
    </div>
    
  </fieldset>
</div>

app/views/sales/edit.html.erb
<h1>Editar Venda</h1>

<%= render 'form', sale: @sale %>

app/views/sales/index.html.erb
<div class=" d-flex">
		<div class="col-10">
		  <h1><%= Sale.model_name.human(count: @sales.count) %></h1>
		</div>
		
		<div class="col-2">
		  <%= link_to t('links.new_sale'), new_sale_path, class:"btn btn-primary float-right" %>
		</div>
</div>
</br>

<table class="table table-hover">
  <thead class="table-dark">
    <tr>
      <th><%= @sales.human_attribute_name(:client_id) %></th>
      <th><%= t('description') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.client.name %></td>
        <td><% sale.products.each do | product | %>
          <p><%= product.name %></p>
        <% end %>
        </td>
        <td><%= link_to t('links.edit'), edit_sale_path(sale), class: "btn btn-primary" %></td>
        <td><%= link_to t('links.delete'), sale, method: :delete, data: { confirm: t('messages.confirm')}, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/sales/new.html.erb
<h1>Nova Venda</h1>

<%= render 'form', sale: @sale %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <td><%= @sale.client.name %></td>
  <strong>Client:</strong>
  <%= @sale.client_id %>
</p>

<p>
  <td><%= @sale.products.name %></td>
  <strong>Product:</strong>
  <%= @sale.product_id %>
</p>

<%= link_to 'Editar', edit_sale_path(@sale) %> |
<%= link_to 'Voltar', sales_path %>